# generated by datamodel-codegen:
#   filename:  sprotty/actions/action.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Action(BaseModel):
    kind: str
    requestId: Optional[str] = None
