# generated by datamodel-codegen:
#   filename:  sprotty/actions/allSelected.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from .action import Action


class Kind(Enum):
    allSelected = 'allSelected'


class AllSelected(Action):
    kind: Kind
    select: bool
