# generated by datamodel-codegen:
#   filename:  sprotty/actions/elementSelected.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from .action import Action


class Kind(Enum):
    elementSelected = 'elementSelected'


class ElementSelected(Action):
    kind: Kind
    selectedElementsIDs: List[str]
    deselectedElementsIDs: List[str]
    preventOpenSelection: bool
