# generated by datamodel-codegen:
#   filename:  sprotty/actions/fit.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from .action import Action


class Kind(Enum):
    fit = 'fit'


class Fit(Action):
    kind: Kind
    elementIds: List[str]
    maxZoom: float
    animate: bool
