# generated by datamodel-codegen:
#   filename:  sprotty/actions/requestBounds.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from ...klighd import SKGraphSchema
from .action import Action


class Kind(Enum):
    requestBounds = 'requestBounds'


class RequestBounds(Action):
    kind: Kind
    newRoot: SKGraphSchema.SKGraph
