# generated by datamodel-codegen:
#   filename:  sprotty/actions/updateModel.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from ...klighd import SKGraphSchema
from .action import Action


class Kind(Enum):
    updateModel = 'updateModel'


class UpdateModel(Action):
    kind: Kind
    newRoot: SKGraphSchema.SKGraph
