# generated by datamodel-codegen:
#   filename:  sprotty/diagramAccept.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ..lsp.requestMessage import RequestMessage
from .actions import action


class Method(Enum):
    diagram_accept = 'diagram/accept'


class ClientId(Enum):
    sprotty = 'sprotty'


class Params(BaseModel):
    clientId: ClientId
    action: action.Action


class DiagramAccept(RequestMessage):
    method: Method
    params: Params
