# generated by datamodel-codegen:
#   filename:  sprotty/diagramOpenInTextEditor.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ..lsp import range
from ..lsp.requestMessage import RequestMessage


class Method(Enum):
    diagram_openInTextEditor = 'diagram/openInTextEditor'


class Location(BaseModel):
    uri: str
    range: range.Range


class Params(BaseModel):
    location: Location
    forceOpen: bool


class DiagramOpenintexteditor(RequestMessage):
    method: Method
    params: Params
