# generated by datamodel-codegen:
#   filename:  klighd/actions/checkedImages.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    checkedImages = 'checkedImages'


class NotCachedImage(BaseModel):
    k: str
    v: str


class CheckedImages(Action):
    kind: Kind
    notCached: List[NotCachedImage]
    responseId: str
