# generated by datamodel-codegen:
#   filename:  klighd/actions/checkImages.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    checkImages = 'checkImages'


class Image(BaseModel):
    bundleName: str
    imagePath: str


class CheckImages(Action):
    kind: Kind
    images: List[Image]
