# generated by datamodel-codegen:
#   filename:  klighd/actions/performAction.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action


class Kind(Enum):
    performAction = 'performAction'


class PerformAction(Action):
    kind: Kind
    actionId: str
    kGraphElementId: str
    kRenderingId: str
    revision: float
