# generated by datamodel-codegen:
#   filename:  klighd/actions/refreshDiagram.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    refreshDiagram = 'refreshDiagram'


class Options(BaseModel):
    needsClientLayout: Optional[bool] = None
    needsServerLayout: Optional[bool] = None


class RefreshDiagram(Action):
    kind: Kind
    options: Optional[Options] = None
