# generated by datamodel-codegen:
#   filename:  klighd/actions/storeImages.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action
from . import checkedImages


class Kind(Enum):
    storeImages = 'storeImages'


class Images(BaseModel):
    k: checkedImages.NotCachedImage
    v: str


class StoreImages(Action):
    kind: Kind
    images: Images
