# generated by datamodel-codegen:
#   filename:  klighd/actions/updateOptions.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from ...sprotty.actions.action import Action
from .. import ValuedSynthesisOption


class Kind(Enum):
    updateOptions = 'updateOptions'


class UpdateOptions(Action):
    kind: Kind
    valuedSynthesisOptions: List[ValuedSynthesisOption]
    layoutOptions: List
    actions: List
    modelUri: str
