# generated by datamodel-codegen:
#   filename:  lsp/generalSendMessage.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from .requestMessage import RequestMessage


class Method(Enum):
    general_sendMessage = 'general/sendMessage'


class GeneralSendmessage(RequestMessage):
    method: Method
    params: List[str]
