# generated by datamodel-codegen:
#   filename:  lsp/message.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Jsonrpc(Enum):
    field_2_0 = '2.0'


class Message(BaseModel):
    jsonrpc: Jsonrpc
