# generated by datamodel-codegen:
#   filename:  lsp/responseMessage.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from typing import Any, Optional, Union

from .message import Message


class ResponseMessage(Message):
    id: Optional[Union[float, str]]
    result: Optional[Any] = None
    error: Optional[Any] = None
