# generated by datamodel-codegen:
#   filename:  klighd/messages/diagramOptionsSetLayoutOptions.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List

from pydantic import BaseModel

from ...lsp.requestMessage import RequestMessage


class Method(Enum):
    keith_diagramOptions_setLayoutOptions = 'keith/diagramOptions/setLayoutOptions'


class LayoutOption(BaseModel):
    optionId: str
    value: Any


class Params(BaseModel):
    layoutOptions: List[LayoutOption]
    uri: str


class KeithDiagramoptionsSetlayoutoptions(RequestMessage):
    method: Method
    params: Params
