# generated by datamodel-codegen:
#   filename:  klighd/messages/diagramOptionsSetSynthesisOptions.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel

from ...lsp.requestMessage import RequestMessage
from .. import ValuedSynthesisOption


class Method(Enum):
    keith_diagramOptions_setSynthesisOptions = (
        'keith/diagramOptions/setSynthesisOptions'
    )


class Params(BaseModel):
    synthesisOptions: List[ValuedSynthesisOption]
    uri: Optional[str] = None


class KeithDiagramoptionsSetsynthesisoptions(RequestMessage):
    method: Method
    params: Params
