# generated by datamodel-codegen:
#   filename:  klighd/messages/preferencesSetPreferences.json
#   timestamp: 2024-11-14T11:48:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from ...lsp.requestMessage import RequestMessage


class Method(Enum):
    keith_preferences_setPreferences = 'keith/preferences/setPreferences'


class Params(BaseModel):
    diagram_shouldSelectDiagram: bool = Field(..., alias='diagram.shouldSelectDiagram')
    diagram_shouldSelectText: bool = Field(..., alias='diagram.shouldSelectText')
    diagram_incrementalDiagramGenerator: bool = Field(
        ..., alias='diagram.incrementalDiagramGenerator'
    )
    diagram_clientLayout: Optional[bool] = Field(None, alias='diagram.clientLayout')


class KeithPreferencesSetpreferences(RequestMessage):
    method: Method
    params: Params
